# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{database_sleuth}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["watsonian"]
  s.date = %q{2010-01-27}
  s.description = %q{Easily find database connection info from common web applications.}
  s.email = %q{watsonian@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/database_sleuth.rb",
     "spec/database_sleuth_spec.rb",
     "spec/drupal/sites/default/settings.php",
     "spec/gallery/config.php",
     "spec/joomla/configuration.php",
     "spec/mediawiki/LocalSettings.php",
     "spec/phpbb/config.php",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/wordpress/wp-config.php",
     "spec/zencart/includes/configure.php"
  ]
  s.homepage = %q{http://github.com/watsonian/database_sleuth}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Easily find database connection info from common web applications.}
  s.test_files = [
    "spec/database_sleuth_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

